### ISSUE TITLE
Is there any limitation to the client-hardware?

### ISSUE THREAD

**Issue by zjulsp** [xieyaxiongfly/Atheros-CSI-Tool#1]
Hi, first thanks for the tool.
Suppose I use an Atheors 9580 NIC as AP with 3 antennas which runs the Atheros-CSI-Tool. Which type of clients can we get the CSI information from the three aspects?
1) chip type, We must use another Atheors-9580 chip or any kind, like Intel, Broadcom etc
2) client's antenna number, clients with two or more antennas supported?
3) Txbeamforming-feature must be supported by the clients?
Thanks

**Comment by xieyaxiongfly** [comment]
Hi, thanks for the interests.
The type of WiFi cards that our tool supports is listed here http://pdcc.ntu.edu.sg/wands/Atheros/DeviceList.html .

1, Generally, the sender/receiver must be a chipset from Atheros, no need to be AR9580.
2, We need the sender/receiver be a laptop/desktop installed with our customized kernel.
3, All the type of Wi-Fi cards in our list support Beamforming feature. The antenna number varies from 1-3.

Hope that answers your question. 

Yaxiong

**Comment by zjulsp** [comment]
Yeah, get it.
Thanks for the reply.
