### ISSUE TITLE
Maintenance Page Not Working

### ISSUE THREAD

**Issue by Tamzeed** [xieyaxiongfly/Atheros-CSI-Tool#28]
Hi, The maintainance page http://pdcc.ntu.edu.sg/wands/Atheros/ is not loading for me. Any one else having the same problem?

**Comment by gustavobraga98** [comment]
Same for me

**Comment by adib2149** [comment]
I can't access it too.

**Comment by gustavobraga98** [comment]
It seems that the adress has changed guys, here it is: http://wands.sg/AtherosCSI/

**Comment by Tamzeed** [comment]
Thank you very much.
